import config from 'config'
export const initPassenger = (pType, roomSequence, leadingGuest) => ({
  id: 0,
  roomSequence: roomSequence,
  isLeadGuest: leadingGuest,
  type: pType,
  title: "Mr",
  firstName: "",
  middleName: "",
  lastName: "",
  nationalityCode: "",
  birthDate: "",
  gender: "",
  country: "",
  countryCode: "",
  address: "",
  city: "",
  state: "",
  zipCode: "",
  district: "",
  phoneNumber: "",
  phoneNumberCountryCode: "",
  homePhoneNumber: "",
  homePhoneNumberCountryCode: "",
  passportNo: "",
  passportIssuingDate: "",
  passportExpiryDate: "",
  fax: "",
  email: "",
  status: "success",
  visaFees: config.defaultVisaFees
});
